#!/usr/bin/env bash
#  display information about subdomains

process()
{
    subdomains=(www lb-01 web-01 web-02)
    if [ "$2" ]; then subdomains=("$2") ; fi
    for sub in "${subdomains[@]}"
    do
        record_type=$(dig www.holberton.online | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -F'\t' '{print $4}')
        ip=$(dig ${sub}."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -F' ' '{print $NF}')
        echo "The subdomain ${sub} is a ${record_type} record and points to ${ip}"
    done
}

process $1 $2
