#!/usr/bin/env bash
# Creating a redirection

apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
service nginx restart
