#!/usr/bin/env bash
# Custom 404 page

apt-get install -y nginx
chown -R "$USER:$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404_error_code.html
echo "" >> /var/www/html/404_error_code.html
sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404_error_code.html;\n' /etc/nginx/sites-available/default
service nginx restart
