#!/usr/bin/env bash
# Set a custom server for knowing which hostname answered
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

chown -R "$USER:$USER" /var/www/html
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404_error_code.html
sed -i '/ location/a error_page 404 /404_error_code.html;\n' /etc/nginx/sites-available/default


sudo sed -i "/ location/a add_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
