#!/usr/bin/env bash
# Set a custom server for knowing which hostname answered
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

name=$(hostname)
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
