#!/usr/bin/env bash
# Set a custom server for knowing which hostname answered

sudo apt-get update -y
sudo apt-get install haproxy=1.5.\* -y

sudo printf %s "

    frontend http
        bind *:80
        mode http
        default_backend nodes

    backend nodes
        balance roundrobin
        server 2770-web-01 35.227.18.212:80 check
        server 2770-web-02 35.185.5.35:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
