#!/usr/bin/env bash
# Manage my process

start_pros() {
    ./manage_my_process &
    sudo touch /var/run/my_process.pid
    if [ $# -ne 0 ]
    then
        echo "$1"
    fi
}

stop_pros() {
    sudo rm /var/run/my_process.pid
    if [ $# -ne 0 ]
    then
        echo "$1"
    fi
    pkill -f "manage_my_process"
}

if [ $# == "0" ] || [ $1 == "" ]
then
    echo "Usage: manage_my_process {start|stop|restart}"
    exit;
elif [ $1 == "start" ]
then
    start_pros "manage_my_process started"
elif [ $1 == "stop" ]
then
    stop_pros "manage_my_process stopped"
elif [ $1 == "restart" ]
then
    sudo rm /var/run/my_process.pid
    pkill -P $$
    start_pros "manage_my_process restarted"
fi
