#!/usr/bin/env bash
# gives you information about the holbertonschool file
for ((i=1;i<=100;i++))
do
    if ! (( i % 5 )) || ! (( i % 3 ))
    then
        if ! (( i % 3 ))
        then
            echo -n "Fizz"
        fi
        if ! (( i % 5 ))
        then
            echo -n "Buzz"
        fi
        echo ""
    else
        echo "$i"
    fi
done
