#!/usr/bin/env bash
# Writes stuff from 1 to 20
i=1
while [ $i -lt 21 ]
do
    echo "$i"
    case $i in
        4)
            echo "Bad luck from China"
            ;;
        9)
            echo "Bad luck from Japon"
            ;;
        17)
            echo "Bad luck from Italy"
            ;;
    esac
    ((i++))
done
